### ISSUE TITLE
CT PDMP Roadmap & Plan

### ISSUE THREAD

**Issue by thegoodman99** [paladinarcher/accelerators#138]
- [x]  identify tools
- [x] define version control
- [x] define continuous integration
- [x] validate current manual & automated tests
- [x] delegate
- [ ] document continuous testing system
- [ ] define continuous testing SOP
- [ ] define new tests, data, mocks, works items
- [x] Throw these into a word doc on P&A and PDMP sharepoint
