### ISSUE TITLE
CT-Template Enhancement

### ISSUE THREAD

**Issue by thegoodman99** [paladinarcher/accelerators#168]
**Description:**
Enhance the CT Template and CT Tools

**Benefit Hypothesis:**
CT template will be easier to use, offer more useful, and quicker to set up. 

**Acceptance Criteria:**
- [ ] easier to use (better documentation)
- [ ] improved useful (more features)
- [ ] quicker set up (set up task)

NFRs are technical constraints. Simply define them.
