### ISSUE TITLE
Accelerator User Research

### ISSUE THREAD

**Issue by moroni-pickering** [paladinarcher/accelerators#39]
**Description:**
Conduct Accelerator User Research.

**Benefit Hypothesis:**
Each P&A team member will have improved empathy, understanding and will produce better quality accelerators.

**Acceptance Criteria:**
- [x] Product owner representative persona, empathy map, journey map, affinity map
- [x] Full Stack Developer representative persona, empathy map, journey map, affinity map
- [x] Agile team member persona, empathy map, journey map, affinity map

**Nonfunctional Requirements (NFRs):**
- [ ] Use Mural
