### ISSUE TITLE
Enhanced Issue Templates

### ISSUE THREAD

**Issue by moroni-pickering** [paladinarcher/accelerators#5]
As a product owner
I want issue templates that improve quality and ease of creating features, MVPs, stories, and every kind of enablers.
So that we can rapidly create quality work item definitions.

- [x] User Story Template
- [x] Enabler Feature Template
- [x] Business Feature Template
- [x] Enabler Template
- [x] MVP Epic Template
- [x] Feature Epic
- [x] Enabler Feature Epic
- [x] Enabler Content Story
- [x] Enabler Design Prototype Story
- [x] Enabler API Prototype Story
