### ISSUE TITLE
Continuous Testing (CT) Accelerators

### ISSUE THREAD

**Issue by moroni-pickering** [paladinarcher/accelerators#52]
**Enabler Feature Description:** 
Produce accelerators that enable rapid setup of continuous testing (CT).
**Benefit Hypothesis:** 
We expect continuous testing will be achieved if Keola is able to set up continuous testing on his project with templates, code snippets, continuous testing handbook, and checklists.
**Acceptance Criteria:**
- [x] Checklist for establishing Continuous Testing
- [x] A CT Handbook that extends our CT Framework

- [x] Code snippets that will help set up CT

- [x] Templates that can be reused to quickly setup CT (don't commit any project/client-specific code to our public repos)

**Nonfunctional Requirements (NFRs):** 
- [x] Reuse/Reference our Continuous Testing Framework

- [x] Use the technology that Keola is using on his current project

https://paladinarcher-my.sharepoint.com/:w:/p/debra/ETf8vfojsXlHvUIq1yVtSNoBEcDHgZULFocsjkoMicEGFw?e=IyyhPt
