### ISSUE TITLE
Client Case Studies

### ISSUE THREAD

**Issue by moroni-pickering** [paladinarcher/accelerators#63]
**Enabler Feature Description:** 
Success cases, where we improved our clients lives.
A case study of when we made a difference.

**Benefit Hypothesis:** 
We expect the studies to provide many benefits: creation of customer database, success metrics, material for proposals, generating ideas for others on how they might contribute, and recognizing success.

**Acceptance Criteria:**
- [x] 1 page per case
- [x] A success story, case study template for future use

- [x] Are proof points for our noble sales purpose

- [x] 1 per customer facing employee have been added to the repo

- [x] Cases are promoted/shared internally, after adding to the repo

**Nonfunctional Requirements (NFRs):** 
- [x] Use the case study template in microsoft word 

- [x] Store in sharepoint
